services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/postgres
  api:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgresdb
    ports:
      - $API_PORT:$API_PORT
    stdin_open: true
    tty: true

volumes: 
  db: